name: adsdk
description: AdSdk is a wrapper around famous ad packages which let you integrate ads easily.
version: 1.1.0
homepage: https://github.com/Appyhigh/ad-sdk-flutter.git
repository: https://github.com/Appyhigh/ad-sdk-flutter.git

environment:
  sdk: ">=2.18.1 <3.3.0"


dependencies:
  applovin_max: ^3.2.0
  dart_jsonwebtoken: ^2.11.0
  flutter:
    sdk: flutter
  gdpr_dialog: ^2.1.1
  google_mobile_ads: ^3.0.0
  http: any
  plugin_platform_interface: ^2.1.6
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.appyhigh.plugins.adsdk
        pluginClass: AdsdkPlugin
      ios:
        pluginClass: AdsdkPlugin

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf